import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/shared/Navbar";
import { Container } from "@mui/material";
import Footer from "../components/shared/footer";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Container maxWidth="xl">
            <Navbar />
            <div className="min-h-screen">{children}</div>
            <Footer />
          </Container>
      </body>
    </html>
  );
}
